### ISSUE TITLE
Impersonateion not full

### ISSUE THREAD

**Issue by K3nshin66** [S3cur3Th1sSh1t/SharpNamedPipePTH#3]
hi
thanks for this project 
my issue is i got the "sysToken" from "CreateNamedPipeW" and "DuplicateTokenEx" and i got the cmd.exe too
and i become administrator of my test lab AD but when i dir my DC i got "Access is denied."

but when i Impersonate with the regular password i have full permission and dir work
i google the problem ant nothing i even play with "CreateNamedPipeW" securityAttributes still nothing
any idea?

**Comment by S3cur3Th1sSh1t** [comment]
Maybe you were just duplicating the Token from a process, that doesnt have network logon permissions. Some tokens cannot logon over the network. Than you need to impersonate a different process ID's token.

**Comment by K3nshin66** [comment]
just the same your code 

first i  -> ImpersonateNamedPipeClient(hPipe)
after that  ->  OpenThreadToken(GetCurrentThread(), TOKEN_ALL_ACCESS, false, out tokenHandle);
and then  -> DuplicateTokenEx(tokenHandle, TOKEN_ALL_ACCESS, IntPtr.Zero, (int)SECURITY_IMPERSONATION_LEVEL.SecurityDelegation, (int)TOKEN_TYPE.TokenPrimary, out sysToken);

"that doesnt have network logon permissions" btw i got AuthenticationType token with winAPi and i got "Network" rather then "Inter active"

"Than you need to impersonate a different process ID's token" you mean after i become admin of AD?

**Comment by S3cur3Th1sSh1t** [comment]
Ah. Wow I thought you opened up the issue in the SharpImperonation repo. My mistake. The NamedPipePTH technique does not provide you any network level access at all, it’s always local tokens. That’s also described in the blog post. 

So what you want to do doesn’t work. Sorry.
